### PR TITLE
chore(docs): fix the doc of gesture api usage bug

### PR DESCRIPTION
**Pull request by huhm**
wrong call for useGesture/Gesture in the docs

### CODE REVIEW

**Comment by dbismut** [comment]
Hey, you've introduced formatting fixes, why is that?

**Comment by huhm** [comment]
The formatting change (line 29) is just auto fixed by my vscode extensions. 
This commit is not the formatting fixes.  useGesture and new Guesture usage is not correct in the docs. which has  puzzled me when read the document.

**Comment by huhm** [comment]
image
This  right parenthesis should moved here

**Comment by dbismut** [comment]
@huhm sorry for getting back to you this late. I've fixed this elsewhere along with other chore utilities. Thanks for the heads up.

**Pull request closed without merging**
