### PR TITLE
feat: add keys option to disable arrow keys drag

### PR DESCRIPTION
**Pull request by dbismut**

### CODE REVIEW

**Comment by willybrauner** [comment]
Is it an expected behavior that keys can't be disable if target is window? In the this example, keys continue to trigger the drag handler. 

```ts
new DragGesture(window, () => { ... }, {
  eventOptions: { passive: false },
  preventDefault: true,
  pointer: { keys: false }
})
```
I will try to take time to make a reproductible example.

**Comment by dbismut** [comment]
Good catch, that's a bug @willybrauner. Fixing now. Merci ;)

**Comment by dbismut** [comment]
Fixed now @willybrauner in 10.2.22, should be working with Vanilla as well. https://github.com/pmndrs/use-gesture/releases/tag/%40use-gesture%2Fvanilla%4010.2.22

**Comment by willybrauner** [comment]
Wow merci ! 🙏🏽

**Pull request merged**
