### PR TITLE
Add lostPointerCapture event handler for DragEngine

### PR DESCRIPTION
**Pull request by megabuz**
`useDrag` stuck in down state sometimes - see https://github.com/pmndrs/use-gesture/issues/376#issuecomment-1013906164 for details

The problem happens if element looses pointer capture, so pointerUp event can be handled by wrong handler.
This PR adds additional `lostPointerCapture` handler for such cases. In normal cases it should be fired after `pointerUp` and should not have any side effects.

### CODE REVIEW

**Comment by dbismut** [comment]
Hey, thanks for this. Are you positive this actually fixes it? 

Also I would prefer keeping a listener on `pointerup` events and use `lostpointercapture` handler as a backup.

Thanks!

**Comment by megabuz** [comment]
> Are you positive this actually fixes it?

As far as I can test it, yes

> Also I would prefer keeping a listener on pointerup events and use lostpointercapture handler as a backup

I didn't remove listeners from `pointerup` events. In normal cases `pointerup` event should be fired first.

**Comment by dbismut** [comment]
Oh right sorry, I checked the PR from my phone and overlooked one line. I'll review this today or tomorrow. Thanks again.

**Comment by dbismut** [comment]
Hey, I haven't forgotten about this, but it's a bit more complex than expected, because pointer event support is optional, currently this PR doesn't work with the `target` option because how events listeners are translated into React props, I'll have to dig further into this.

**Comment by megabuz** [comment]
> pointer event support is optional

could you elaborate? I don't have enough context here

> this PR doesn't work with the target option because how events listeners are translated into React props

can we use it for cases when `target` option is not set?

**Comment by dbismut** [comment]
**Re: pointer support.** The lib falls back to using mouse events when `PointerEvent` is not supported. Also, there's an option (`pointer.capture = false`) that makes drag rely on attaching handlers to the `window` and skip `setPointerCapture`. In both cases adding a `lostpointercapture` listener to the element doesn't make sense. 

**Re: target option.** This is an implementation detail that might need an overhaul, but the lib tries to attach events whether as props or via `addEventListener` via the same function, and handles camel key casing, plus adding `Capture` to the end of the prop in case the event needs to be treated as passive. Long story short, because `lostPointerCapture` contains the string `Capture`, it messes up the event function in the lib. This is easily fixable but I'll take the opportunity to apply minor adjustments to that function. 

In both cases, I'll take care of this as it would cause you headaches I promise. It just takes a bit more time.

**Pull request merged**
