### PR TITLE
fix: unexpected velocity at end of gesture

### LINKED ISSUE #332: Unexpected velocity at end of drag gesture
**Describe the bug**
Velocity seems to only be recalculated on movement events, making the last velocity likely to be inaccurate. This is notable mostly in cases where movement has stopped entirely.

**Sandbox**
https://codesandbox.io/s/use-gesture-drag-velocity-at-gesture-end-tu9kr?file=/src/index.js
Where it can be noted that dropping the draggable element after having ceased movement often still produces velocity and subsequent animation.

**Commentary**
In the sandbox linked above it might seem like a simple threshold test could be made and if the velocity is below it then further animation is avoided. That would work for probably most cases but would fail for high velocities that are possible after an abrupt halt to the movement (the demo button simulates that scenario). It could probably be worked around with a fairly simple timestamp test but this seems like a something the library could handle without detriment to other use cases.

**Information:**
 - Use Gesture version: 10
 - Device: macbook
 - OS: macOS
 - Browser: Brave

**Checklist:**
  - [ ] I've read the [documentation](https://use-gesture.netlify.app/).
  - [ ] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

### PR DESCRIPTION
**Pull request by stokesman**
To fix #332, now on input events the engine queues an update to a previous movement state value and calculates velocity on last input event using that. 

**How this was tested** 
Besides verifying all unit tests still pass, this was tested manually with a version of the sandbox I'd made for #332 converted into on of the `demo/` sandboxes. If that sounds helpful for testing (or if it's just good to have another vanilla demo) I could submit as another PR.

https://user-images.githubusercontent.com/9000376/126075330-3ab47cc0-7be2-4e0b-b1ea-5c7cc6205777.mp4

### CODE REVIEW

**Comment by dbismut** [comment]
Hi @stokesman I just had a look, thanks a lot for submitting this! A few questions:

> Besides verifying all unit tests still pass

Running `yarn test` does output errors (which is expected), so I'm not sure which unit tests you're referring to?

>  If that sounds helpful for testing (or if it's just good to have another vanilla demo) I could submit as another PR.

You can submit it as part of this PR, that will make it easier to test.

On my end, I've tried outputting the end velocity of the drag, and this is what I got (Firefox, latest version on a MacBook Air M1 trackpad).


https://user-images.githubusercontent.com/5003380/126162645-a4960993-ce2a-4d16-af3f-0df54ce8b7bf.mov

I've tried keeping my gesture consistent, but as you can see, I do get `[0,0]` as the end velocity although it's not supposed to. It doesn't seem to work very differently than setting an arbitrary delay. I'll try to think about this later in the day.

**Comment by dbismut** [comment]
Let me know if I'm wrong, but this is what would happen without and with RAF:

```
# without RAF
Event N : mousedown [10,0] velocity[0,0]
Event N + 10 : mousemove [20,0] velocity[0,1]
Event N + 20 : mousemove [40,0] velocity[0,2]
Event N + 30 : mouseup [40,0] velocity [0,0]


# with RAF
Event N : mousedown [10,0] velocity[0,0] / sent to user [0,0]
Event N + 10 : mousemove [20,0] velocity[0,1] / sent to user [0,0]
(RAF N + 16 : mousemove[20,0] velocity [0,1.25])
Event N + 20 : mousemove [40,0] velocity[0,2] / sent to user [0,1.25]
Event N + 30 : mouseup [40,0] velocity [0,0] / sent to user [0,1.25]
```

Is that right? Essentially what RAF does is that if the last `mouseup` event occurs within a frame, it won't update the velocity and the handler will keep the velocity from the last frame. I don't think it's very different than setting an arbitrary delay of `16ms` before the last `mouseup` event don't you think?

**Comment by stokesman** [comment]
Hi @dbismut, thanks for having the look. I think you've understood this well. 

>Running `yarn test` does output errors (which is expected), so I'm not sure which unit tests you're referring to?

How odd! Here’s what I get from `pnpm test` on this branch:
image
And on `v10`:
image

>…on a MacBook Air M1 trackpad

I usually use a mouse but I've tried with my trackpad on my MacBook and, for me, it's more challenging to produce either result (a drop with or without velocity) as intended. Does this feel the same to you as the solution you've tried?

>I don't think it's very different than setting an arbitrary delay of 16ms before the last mouseup event don't you think?

I agree that they don't seem very different. I think I understand what you've tried with the arbitrary delay (not so much a delay but a threshold for whether or not to recalculate velocity?) but I haven't seen it to know. It may be effectively the same.

**Comment by dbismut** [comment]
Hey @stokesman sorry for the late reply, I've been busy with holidays and quitting my job :) Anyway, I've just created PR #347 which you could try with your demo, when you have time!

**Comment by stokesman** [comment]
> I've been busy with holidays and quitting my job :)
Here's to quitting jobs 🍺 

Closing this as #347 does it better 🎉

**Comment by dbismut** [comment]
Great news! Now released as `10.0.0-beta.26`, I guess this should be the last beta release before stable.

**Pull request closed without merging**
